server:
  port: 7883
spring:
  application:
    name: consumer_2
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.3.29:9092
          zk-nodes: 192.168.3.29:2181
          auto-create-topics: true
      bindings:
        input_user_project:
          destination: user_project
          group: consumer_2
        input_user_task:
          destination: user_task
          group: consumer_2